baseurl = "https://www.graphsys.com/"
title = "GraphSys"
author = "Joze Rozanec"
languagecode = "en"
theme = "ananke"

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[[menu.main]]
    name = "Call for papers"
    url  = "/call-for-papers"

[[menu.main]]
    name = "Organizers and Committee"
    url  = "/organizers-and-committee"

[[menu.main]]
    name = "Program"
    url  = "/program"

[[menu.main]]
    name = "Keynotes"
    url  = "/keynotes"

[[menu.main]]
    name = "Previous editions"
    url  = "/previous-editions"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params.ananke.social.linkedin]
username = "graphsys"

[params]
mainSections = ["post"]
text_color = ""
author = "GraphSys" # default author, override via `author` in a posts front matter
favicon = ""
site_logo = ""
description = "Workshop on Serverless, Extreme-Scale, and Sustainable Graph Processing Systems"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"

customCSS = ["/css/custom.css"]
